instagram/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('photos.urls')),
    url(r'^', include('comments.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls))

]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

photos/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView, RedirectView

from photos.views import UserLoginView, UserLogoutView, PhotoCreateView, PhotoDetailView, PhotoDeleteView, PhotoListView, \
    LikeView

urlpatterns = [
    url(r'photo/(?P<pk>[\d]+)/delete/$', PhotoDeleteView.as_view(), name='delete_photo'),
    url(r'feed/$', PhotoListView.as_view(), name="feed"),
    url(r'photo/(?P<pk>[\d]+)/like/$', LikeView.as_view(), name="like_dislike"),
    url(r'add-new/$', PhotoCreateView.as_view(), name="add_new"),
    url(r'photo/(?P<pk>[\d]+)/$', PhotoDetailView.as_view(), name='photo_detail'),
    url(r'login/$', UserLoginView.as_view(), name="login"),
    url(r'logout/$', UserLogoutView.as_view(), name="logout"),
    url(r'^$', RedirectView.as_view(url='/feed/'), name='main'),


]

comments/models.py
from django.contrib.auth import get_user_model
from django.db import models

from photos.models import Photo, BaseModel

User = get_user_model()


class Comment(BaseModel):
    text = models.TextField()
    user = models.ForeignKey(User, related_name="comments")
    photo = models.ForeignKey(Photo, related_name="comments")

    class Meta:
        ordering = ('-create_date',)

    def __str__(self):
        return self.text

photos/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls.base import reverse

User = get_user_model()


class BaseModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ["pk"]


class Photo(BaseModel):
    image = models.ImageField(upload_to='photos')
    user = models.ForeignKey(User, related_name='photos')
    likes_count = models.PositiveIntegerField(default=0)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('photo_detail', kwargs={'pk': self.id})

    def get_photo_comments(self):
        return self.comments.all()


class Like(BaseModel):
    user = models.ForeignKey(User, related_name='likes')
    photo = models.ForeignKey('Photo', related_name='likes')

photos/forms.py
from django.forms.models import ModelForm

from photos.models import Photo


class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'description']

photos/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.http.response import JsonResponse
from django.urls.base import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView
from django.db.models import Prefetch

from comments.forms import CommentForm
from photos.decorators import only_image_owner
from photos.forms import PhotoForm
from photos.models import Photo, Like


User = get_user_model()


class UserLoginView(LoginView):
    template_name = 'login.html'


class UserLogoutView(LogoutView):
    next_page = '/login/'


class PhotoCreateView(CreateView):
    model = Photo
    template_name = 'add_new_photo.html'
    form_class = PhotoForm

    @method_decorator(login_required(login_url='login'))
    def dispatch(self, *args, **kwargs):
        return super(PhotoCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super(PhotoCreateView, self).form_valid(form)



class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'photo_detail.html'
    context_object_name = 'photo'

    @method_decorator(login_required(login_url='login'))
    def dispatch(self, *args, **kwargs):
        return super(PhotoDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PhotoDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        context['comment_form'] = form
        context['photo_comments'] = kwargs['object'].get_photo_comments()
        return context



class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = reverse_lazy('feed')
    template_name = 'photo_detail.html'

    @method_decorator(login_required(login_url='login'))
    @only_image_owner
    def dispatch(self, *args, **kwargs):
        return super(PhotoDeleteView, self).dispatch(*args, **kwargs)


class PhotoListView(ListView):
    model = Photo
    paginate_by = 10
    template_name = 'feed.html'
    context_object_name = 'photos_list'
    ordering = '-create_date'

    @method_decorator(login_required(login_url='login'))
    def dispatch(self, *args, **kwargs):
        return super(PhotoListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super(PhotoListView, self).get_queryset().select_related('user')
        return queryset.prefetch_related(
            Prefetch("likes", queryset=Like.objects.filter(user=self.request.user))
        )

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        form = CommentForm()
        context['comment_form'] = form
        return context


class LikeView(View):

    @method_decorator(login_required(login_url='login'))
    def dispatch(self, *args, **kwargs):
        return super(LikeView, self).dispatch(*args, **kwargs)

    def post(self, request, pk):
        user = request.user
        photo = Photo.objects.get(id=pk)
        instance, created = Like.objects.get_or_create(photo=photo, user=user)
        if not created:
            instance.delete()
            liked = False
        else:
            liked = True
        photo.likes_count = Like.objects.filter(photo=photo).count()
        photo.save()
        return JsonResponse({"liked": liked, "likes_count": photo.likes_count})

photos/templates/add_new_photo.html
{% extends 'base.html' %}
{% block content %}
  <form method="POST" action="{% url 'add_new' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add photo">
  </form>
{% endblock %}

photos/templates/feed.html
{% extends 'base.html' %}
{% load photo_tags %}
{% block content %}

  <div style="display: none" id="csrf_token">{% csrf_token %}</div>
  {% for photo in photos_list %}
    <div class="row hr-divider">
      <div class="col-sm-6 col-sm-offset-3 col-md-12 col-xs-12">
        <div class="image-container">

          <div class="user-info"> {{ photo.user.username }}</div>
          <div class="user-info">{{ photo.user.email }}</div>
          <p>Likes:</p>
          <div class="likes-count">{{ photo.likes_count }}</div>

          {% show_like_button photo %}

          <div><a href="{% url 'photo_detail' pk=photo.id %}"><img src="{{ photo.image.url }}" class="thumbnail"></a>
          </div>
          <button type="button" class="show-comments-btn btn btn-primary">Show comments</button>
          <div class="comments-container" style="display: none;" data-comments-url="{% url 'comments' pk=photo.id %}">

            <form class="comment-form" method="POST" data-action="{% url 'comment' pk=photo.id %}">
              {% csrf_token %}
              <div class="form-group">
                <label for="id_text">Comment:</label>
                <p class="form-errors"></p>
                <textarea name="text" id="id_text" class="form-control" rows="5"></textarea>
              </div>
              <input type="submit" value="Submit" class="btn btn-primary">

            </form>

            <div class="photo-comments"></div>
          </div>

        </div>
      </div>
    </div>
  {% endfor %}

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>

  {% endif %}
{% endblock %}

photos/templates/login.html
{% extends 'base.html' %}
{% block content %}

  <div class="container">

    <form class="form-signin" action="{% url 'login' %}" method="POST">
      {% csrf_token %}
      <h2 class="form-signin-heading">Please sign in</h2>
      <label for="id_username" class="sr-only">Username: </label>
      <input type="text" id="id_username" name="username" class="form-control" placeholder="Username" required
             autofocus>
      <label for="id_password" class="sr-only">Password</label>
      <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" required>
      <div class="checkbox">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
    {% if form.errors %}
      <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
      {% if user.is_authenticated %}
        <p class="error_login">Your account doesn't have access to this page. To proceed,
          please login with an account that has access.</p>
      {% else %}
        <p>Please login to see this page.</p>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}

photos/templates/photo_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-12 col-xs-12">
      {% if photo.user == user %}
        <form action="{% url 'delete_photo' pk=photo.id %}" method="post">{% csrf_token %}
          <input type="submit" value="Delete" class="btn btn-primary"/>
        </form>
      {% endif %}
    <div class="image-container">
      <img src="{{ photo.image.url }}" class="thumbnail">
      <div>Description: {{ photo.description }}</div>
      <div>Username: {{ photo.user.username }}</div>
      <div>Email: {{ photo.user.email }}</div>
      <div>Date added: {{ photo.create_date }}</div>
      <div>Likes: {{ photo.likes_count }}</div>
      <button type="button" class="show-comments-btn btn btn-primary">Show comments</button>
      <div class="comments-container" data-comments-url="{% url 'comments' pk=photo.id %}">
        <form method="POST" class="comment-form" data-action="{% url 'comment' pk=photo.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_text">Comment:</label>
             <p class="form-errors"></p>
            <textarea name="text" id="id_text" class="form-control" rows="5"></textarea>
          </div>
          <input type="submit" value="Submit" class="btn btn-primary">

        </form>
{#        {% for comment in photo_comments %}#}
{#          <div>{{ comment.user.username }}</div>#}
{#          <div>{{ comment.text }}</div>#}
{#        {% empty %}#}
{#          <p>No comments yet. Be the first! </p>#}
{#        {% endfor %}#}
       <div class="photo-comments"></div>
      </div>
    </div>
    </div>
  </div>
{% endblock %}